### ISSUE TITLE
unknown error in cloudbuild with firebase image

### ISSUE THREAD

**Issue by MatteoGioioso** [firebase/firebase-tools#2004]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

### [REQUIRED] Test case

my `cloudbuild.yaml`

```
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'boostrap']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy']
```
### [REQUIRED] Steps to reproduce

Cannot reproduce as there is no stack trace

### [REQUIRED] Expected behavior

Should deploy normally

### [REQUIRED] Actual behavior

`cloudbuild build step 2 "gcr.io/myprojectid/firebase" failed: step exited with non-zero status: 2`

```
omplete
Step #2: dbdc36973392: Pull complete
Step #2: f59d6d019dd5: Pull complete
Step #2: aaef3e026258: Pull complete
Step #2: 6e454d3b6c28: Pull complete
Step #2: c717a7c205aa: Pull complete
Step #2: d9f6b0e15f1d: Pull complete
Step #2: e3648f5f820f: Pull complete
Step #2: eb3c4cbb1436: Pull complete
Step #2: bc9219ed772b: Pull complete
Step #2: 20edabc35ba3: Pull complete
Step #2: Digest: sha256:9fe4bd13cb59d718fd09db60ebb58a4b0626729c178bda95628a78e673e38ffc
Step #2: Status: Downloaded newer image for gcr.io/myimageid/firebase:latest
Step #2: gcr.io/myimageid/firebase:latest
Step #2: 
Step #2: Error: An unexpected error has occurred.
Finished Step #2
ERROR
ERROR: build step 2 "gcr.io/myprojectid/firebase" failed: step exited with non-zero status: 2
```

I am sorry I cannot give you more details, but there is no stack trace on the cloudbuild logs, just this unknown error. Also it has been a while since I did not deploy this application, I might have missed some update or something
