### ISSUE TITLE
How to run `firebase emulators:exec` on github actions?

### ISSUE THREAD

**Issue by Ridermansb** [firebase/firebase-tools#2337]
I'm trying to make this working on Github Actions by running `firebase  emulators:exec`, but this command [requires java][1].

I'm receiving 

>Error: firestore: Firestore Emulator has exited because java is not installed, you can install it from https://openjdk.java.net/install/

on Github Actions CI when on step...

```
      - name: Setting-up JAVA
        uses: actions/setup-java@v1.3.0
        with: 
          java-version: "12.x"
      - name: Test
        uses: w9jds/firebase-action@v1.3.1
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GCLOUD_PROJECT: ${{ secrets.nextGCLOUD_PROJECT }}
          PROJECT_ID: ${{ secrets.nextFIREBASE_PROJECTID }}
        with:
          args: emulators:exec --only functions,firestore \"npm run test --exit -- --forceExit --detectOpenHandles\"
```

I already post this question [on Stackoverflow][2] but still no answer.

I was thinking if anyone here can help me with that?

[1]: https://github.com/firebase/firebase-tools/blob/de523a9cdf303444dc83700d3d816b90bc18a75b/src/emulator/downloadableEmulators.ts#L261
[2]: https://stackoverflow.com/questions/62055310/run-firebase-emulators-on-github-actions/62198884?noredirect=1#comment110058072_62198884
