### ISSUE TITLE
Cant install to bitbucket pipelines?

### ISSUE THREAD

**Issue by Kolyall** [firebase/firebase-tools#2697]
### [REQUIRED] Environment info

**firebase-tools:**
firebase-tools version 8.0.1

**Platform:**

bitbucket pipelines/ Ubuntu

### [REQUIRED] Steps to reproduce

That is `bitbucket-pipelines.yml` for bitbucket ci:
```

pipelines:
  custom:
    firebaseBuildUpload:
      - step:
          name: Upload to Firebase
          image: java:8
          size: 2x # Double resources available for this step.

          script:
            - apt-get update -y
            - apt-get install -y curl
            - curl -sL https://firebase.tools | bash 
```

In result logs on Pipelines:

```
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
bash: line 242: sudo: command not found
-- Setting permissions on binary...
bash: line 247: sudo: command not found
bash: line 255: /usr/local/bin/firebase: No such file or directory
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
```

### [REQUIRED] Expected behavior

firebase-tools should be successfully installed on machine 

### [REQUIRED] Actual behavior
Something went wrong, firebase has not been installed.
