### ISSUE TITLE
Incorrect permission to the firebase-tools.json file when installing the emulator, incorrect permission to install the emulator.

### ISSUE THREAD

**Issue by siarheidudko** [firebase/firebase-tools#2717]
After version firebase-tools@8.9.2, there is a problem with permissions when running the emulator in GitHub Actions on Ubuntu@latest (Ubuntu@18.04.5 LTS)

With a simple global installation in GitHub Actions after the version firebase-tools@8.9.2 unable to start the emulator:
`sudo npm i firebase-tools -g`
`firebase emulators:exec --only firestore 'node -v'`
However, the latest working version:
`sudo npm i firebase-tools@8.9.2 -g`
`firebase emulators:exec --only firestore 'node -v'`

Error message:
`EACCES: permission denied, open '/home/runner/.config/configstore/firebase-tools.json'`

To run the emulator on the latest version you have to correct the permission:
`sudo npm i firebase-tools -g`
`sudo firebase setup:emulators:firestore`
`sudo chmod 0755 /home/runner/.config/configstore/firebase-tools.json`
`firebase emulators:exec --only firestore 'node -v'`

Changing the global installation directory for npm does not help, because this does not apply directly to the library, but to the emulator. It is also not possible to start firebase without first installing the emulator and correcting permission, since installing the emulator now requires superuser permission.

This is only a problem for the emulator, since there were no permission issues before version 8.9.2 inclusive.

**Comment by yuchenshi** [comment]
I'm not the expert on this topic, but based on my personal experience, `npm` commands on GitHub Actions should not need `sudo` and you're usually better off not using `sudo` for any of the commands, since it ends up messing up the permissions.

Have you tried removing `sudo` for `npm i -g` and all other commands? If it still doesn't work, would you mind sharing your workflow YAML file? Feel free to remove things you'd like to keep private, but show the parts where you set up Node.js, npm, and installing CLI + emulators.

**Comment by siarheidudko** [comment]
Packages that are installed globally require superuser permission or change the global package directory. I tried both options, but the problem is not in the package, but in the emulator that it installs. It is installed in a protected area and requires elevated permission.

If you remove all the extra stuff we will end up with these yml's.
There is nothing special in the **firebase** directory, you can take any project (for example, initialize a new one)

Fixed workflow:
```
name: Example workflow
on:
  push:
    branches:
      - development
jobs:
  test:
    name: Example job
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 12
    timeout-minutes: 15
    steps:
      - name: Unzip the directory with the main project
        uses: actions/download-artifact@v2
        with:
          name: firebase
          path: ${{ github.workspace }}/firebase
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install test & build dependencies
        run: sudo npm install firebase-tools typescript eslint nyc mocha -g
      - name: Install emulator (it is fix 1)
        run: sudo firebase setup:emulators:firestore
      - name: Change permission (it is fix 2)
        run: sudo chmod 0755 /home/runner/.config/configstore/firebase-tools.json
      - name: test1
        run: firebase emulators:exec --only firestore 'node -v'
        working-directory: ${{ github.workspace }}/firebase
```

Old workflow (works with versions below 8.9.2):
```
name: Example workflow
on:
  push:
    branches:
      - development
jobs:
  test:
    name: Example job
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 12
    timeout-minutes: 15
    steps:
      - name: Unzip the directory with the main project
        uses: actions/download-artifact@v2
        with:
          name: firebase
          path: ${{ github.workspace }}/firebase
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install test & build dependencies
        run: sudo npm install firebase-tools@8.9.2 typescript eslint nyc mocha -g
      - name: test1
        run: firebase emulators:exec --only firestore 'node -v'
        working-directory: ${{ github.workspace }}/firebase
```
