### ISSUE TITLE
firebase deploy --only functions without node_modules

### ISSUE THREAD

**Issue by fly1ted** [firebase/firebase-tools#274]
From the docs I concluded that it's not necessary to have local pckgs in node_modules installed for GCS to operate: it should install them in the instance based on package.json. So, I deleted node_modules coz it seemed that it uploads and takes some time to do that. However I get an err. Anyone else has this?

```
i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
+  runtimeconfig: all necessary APIs are enabled
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module 'firebase-functions'

Try running "npm install" in your functions directory before deploying.
```

**Comment by mbleigh** [comment]
The Firebase CLI executes your code locally in order to parse the triggers, so you must have `node_modules` locally in order to deploy. However, when we pack up the functions directory to upload we ignore `node_modules` so whether it's there or not will not impact deploy time.

**Comment by jjhesk** [comment]
what is the solution?

**Comment by laurenzlong** [comment]
Hi @jjhesk , run the following inside of your functions directory:

```
npm install
firebase deploy 
```

**Comment by ralphsmith80** [comment]
I ran into this and struggled with it for a bit so just to add some help to others that might run across this and not see the obvious answer.

If you're using some kind of automated pipeline then you will likely need to specifically add the `cd functions && npm install && cd -` to the runner. Below is an example `.gitlab-ci.yml` that I use for for a gitlab polymer project.

I think I got hung up on this because I didn't have to do that step locally when I first setup the project. Likely `firebase init` just did it for me.

```
image: node:6

before_script:
  - npm install -g firebase-tools
  - npm install -g bower
  - npm install -g polymer-cli

cache:
  paths:
    - node_modules/
    - functions/node_modules/
    - bower_components/

deploy_to_firebase:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    # cd to the functions directory and `npm install` so firebase-functions is installed
    - cd functions && npm install && cd -
    - bower install --allow-root
    - polymer build
    - firebase use --token $FIREBASE_DEPLOY_KEY
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
```
