### ISSUE TITLE
Github Actions - firebase-deploy and GOOGLE_APPLICATION_CREDENTIALS failing to auth

### ISSUE THREAD

**Issue by asc-adean** [firebase/firebase-tools#2863]
Hi,

I'm attempting to authenticate to Firebase using GOOGLE_APPLICATION_CREDENTIALS secrets, but I am not able to authenticate against Firebase.

### [REQUIRED] Environment info

Latest version of firebase-deploy provided by Github Actions?

**Platform:** Ubuntu

### [REQUIRED] Test case

```
     - name: Echo Google Credentials to file
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS_JSON > $PWD/firebase.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase.json

      - name: Deploy to firebase
        #if: env.REF != 'master'
        uses: ./.github/actions/firebase-deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          ref: ${{ env.REF }}
          configuration: ${{ needs.setup.outputs.configuration }}
          file_path: ./${{ env.ANDROID_APP_NAME }}.${{ env.ANDROID_FILE_TYPE }}
          pr_branch_app_id: ${{ secrets.FIREBASE_ANDROID_PR_APP_ID }}
          develop_branch_app_id: ${{ secrets.FIREBASE_ANDROID_DEV_APP_ID }}
          master_branch_app_id: ${{ secrets.FIREBASE_ANDROID_PROD_APP_ID }}
```

### [REQUIRED] Steps to reproduce

1. Create key in IAM/Firebase auth
2. Copy contents of JSON file into a Github secret named **GOOGLE_APPLICATION_CREDENTIALS** or something that can be referenced in the next step
3. Reference secret in github action tasks (either referencing directly or echoing to a file and referencing the path)

### [REQUIRED] Expected behavior

Login using GOOGLE_APPLICATION_CREDENTIALS file

### [REQUIRED] Actual behavior

```
Run ./.github/actions/firebase-deploy

Error: Failed to authenticate, have you run firebase login?
Error: Process completed with exit code 1.
```

**Comment by asc-adean** [comment]
Finally found enough clues to fix it.  Here's my solution:

Secret name **GOOGLE_APPLICATION_CREDENTIALS_JSON** contains a copy/paste of the json file (not base64'd or anything)

```
     - name: Print GOOGLE_APPLICATION_CREDENTIALS_JSON to file
        shell: bash
        run: 'echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > firebase.json'
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

...

     - name: Deploy to firebase
        #if: env.REF != 'master'
        uses: ./.github/actions/firebase-deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./firebase.json
        with:
          ref: ${{ env.REF }}
          #firebase_token: ${{ secrets.FIREBASE_TOKEN }}
          configuration: ${{ needs.setup.outputs.configuration }}
          file_path: ./${{ env.ANDROID_APP_NAME }}.${{ env.ANDROID_FILE_TYPE }}
          pr_branch_app_id: ${{ secrets.FIREBASE_ANDROID_PR_APP_ID }}
          develop_branch_app_id: ${{ secrets.FIREBASE_ANDROID_DEV_APP_ID }}
          master_branch_app_id: ${{ secrets.FIREBASE_ANDROID_PROD_APP_ID }}
```
