### ISSUE TITLE
firebase init hosting ignores --project option

### ISSUE THREAD

**Issue by MasaGon** [firebase/firebase-tools#2916]
### [REQUIRED] Environment info

**firebase-tools:8.18.1**

**Platform:Ubuntu on Window WSL**

### [REQUIRED] Test case

`firebase init hosting --project <project_alias>`

### [REQUIRED] Steps to reproduce

`firebase init hosting --project staging` on multiple project environment.

[.firebaserc]
```json
{
  "projects": {
    "default": "project1",
    "staging": "project2",
    "production": "project3",
    "development": "project1"
  }
}
```

### [REQUIRED] Expected behavior

`.github/workflows/firebase-hosting-merge.yml` tied to project2 firebase service account.

```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - release/staging
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT2 }}'
          channelId: live
          projectId: dy-development
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

### [REQUIRED] Actual behavior

`.github/workflows/firebase-hosting-merge.yml` tied to default firebase service account. And secret on GitHub should also be created.

```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - release/staging
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT1 }}'
          channelId: live
          projectId: dy-development
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

By the way, I already run `firebase use staging`.

**Comment by samtstern** [comment]
@MasaGon thank you for the report!

@jamesdaniels or @jhuleatt can you take a look? This has to do with the Hosting GitHub Action

**Comment by emmanuelvlad** [comment]
Any update on this issue?

**Comment by davidlunadeleon** [comment]
Hi, I'm currently facing the same problem. 

Is there any update on this issue?

I think the current workaround is to create a GitHub actions service account manually, as suggested in [Setting up the service account](https://github.com/FirebaseExtended/action-hosting-deploy/blob/main/docs/service-account.md) in the docs of ` action-hosting-deploy`. Is this right? 😄

**Comment by aalej** [comment]
Hey y’all, I'm unable to reproduce this issue using the latest version of firebase-tools, currently 15.7.0. Using a `.firebaserc` similar to the one provided in the sample, running `firebase init hosting --project staging` to setup automatic deploys with GitHub will create the ff workflow, which correctly uses the `[REDACTED]-staging` project ID:
```yaml
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_[REDACTED]_STAGING }}
          channelId: live
          projectId: [REDACTED]-staging
```


I’ll be closing this as it seems like this was fixed. If you’re still encountering this issue when using the latest version of firebase-tools, I would recommend opening up a new report with the relevant details so we could investigate further.
