### ISSUE TITLE
`curl -sL firebase.tools | bash` hangs on GitHub Actions

### ISSUE THREAD

**Issue by FanchenBao** [firebase/firebase-tools#3429]
### [REQUIRED] Environment info

**firebase-tools:** N/A. The problem is not with `firebase-tools` but with the installation script of `firebase-tools`.

**Platform:** Linux fv-az193-897 5.4.0-1047-azure #49-Ubuntu SMP Thu Apr 22 14:30:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### [REQUIRED] Test case

N/A. The problem is not with `firebase-tools` but with the installation script of `firebase-tools`.

### [REQUIRED] Steps to reproduce

1. Set up GitHub Actions with the following reproducible yaml file:

```yaml
name: demo
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  demo_firebase_tools_install_hang:
    runs-on: ubuntu-latest
    steps:
      - name: Install Firebase CLI
        run: |
          curl -sL firebase.tools | bash
```

2. Trigger this on GitHub Actions.

### [REQUIRED] Expected behavior

`curl -sL firebase.tools | bash` executes without problem.

### [REQUIRED] Actual behavior

The installation script hangs indefinitely.

### Root Cause
The cause of the hang is Line 99:

```bash
CID=$(cat /dev/urandom | LC_CTYPE=c tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
```
For whatever reason, this command does not terminate in GitHub Actions (it does terminate in other Linux platform I have tested on). It might be due to the way virtual machine is set up in GitHub Actions, such that using the SIGPIPE magic to terminate `cat /dev/urandom` no longer works. For what is worth, I have tried placing `trap SIGPIPE` in the script to reset `SIGPIPTE`, but that still didn't resolve the hanging problem.

### Proposed Solution
The solution I am proposing comes from [here](https://askubuntu.com/a/1124770/1193746). Briefly, instead of relying on the SIGPIPE magic, we can explicitly close the pipe by only retrieving finite amount of `/dev/urandom`. Hence, this command will not hang:

```bash
CID=$(head -80 /dev/urandom | LC_CTYPE=c tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
```
I have tested it on GitHub Actions, and the modified command works as expected. Therefore, I propose changing Line 99 of the installation script from `cat /dev/urandom` to `head -80 /dev/urandom`.
