### ISSUE TITLE
`GOOGLE_APPLICATION_CREDENTIALS` doesn't accept workload identity federation

### ISSUE THREAD

**Issue by jebibot** [firebase/firebase-tools#3926]
### [REQUIRED] Environment info

**firebase-tools: 9.23.0**

**Platform: Ubuntu**

### [REQUIRED] Test case

GitHub Actions workflow:
```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # this automatically exports `GOOGLE_APPLICATION_CREDENTIALS`
      # https://github.com/google-github-actions/auth/blob/abba7c4d9a90b51f27710d62c17077e3e0bc9b78/src/client/workload_identity_client.ts#L196-L214
      # https://github.com/google-github-actions/auth/blob/abba7c4d9a90b51f27710d62c17077e3e0bc9b78/src/main.ts#L104-L106
      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0.4.1
        with:
          create_credentials_file: true
          workload_identity_provider: projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: my-service-account@my-project.iam.gserviceaccount.com

      - name: Run Firebase
        run: firebase projects:list
```

### [REQUIRED] Steps to reproduce

1. Setup Workload Identity Federation according to https://github.com/google-github-actions/auth#setting-up-workload-identity-federation
2. Setup the GitHub Actions workflow above (replace `workload_identity_provider` and `service_account`)
3. Run the GitHub Actions workflow

### [REQUIRED] Expected behavior

Successfully authenticates to Firebase projects

### [REQUIRED] Actual behavior

```
> command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
Error: The incoming JSON object does not contain a client_email field
    at JWT.fromJSON (/opt/hostedtoolcache/node/14.18.1/x64/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/jwtclient.js:195:19)
    at GoogleAuth._cacheClientFromJSON (/opt/hostedtoolcache/node/14.18.1/x64/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:301:16)
    at ReadStream.<anonymous> (/opt/hostedtoolcache/node/14.18.1/x64/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:336:40)
    at ReadStream.emit (events.js:412:35)
    at ReadStream.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by Meuko** [comment]
Soo... any word on this? Still running into this..

**Comment by bkendall** [comment]
This should be fixed by #3972 - keep an eye on that!

**Comment by rockwotj** [comment]
FWIW I have confirmed version 10.1.0 works with this auth method

**Comment by ronba** [comment]
@rockwotj thanks for the PR and for fixing this!!

Did you have to make any changes to your service account configuration to make this work? Right now I'm still hitting a similar error to the one reported:
```
> firebase --version                                                      
10.1.0

> firebase deploy --only hosting:default --debug
[2022-01-17T06:37:58.499Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
...
```

Using a json key file for the same service account the above command works fine.

**Comment by rockwotj** [comment]
@ronba the actual error would be useful, but  by default the GitHub action only asks for GCP scopes, not Firebase ones. You probably need to ask for all the scopes

Here's a snippet of my working config. @bkendall this may be a useful thing to document somewhere 😊

```
name: "..."
jobs:
  preview_frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      deployments: 'write'
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.4.4'
      with:
        token_format: 'access_token'
        access_token_scopes: 'email, openid, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase'
        workload_identity_provider: 'projects/redacted/locations/global/workloadIdentityPools/redacted/providers/redacted'
        service_account: 'redacted@redacted.iam.gserviceaccount.com'
        create_credentials_file: true
```

**Comment by ronba** [comment]
@rockwotj thank you very much!

In my case it ended up being a misconfiguration in the identity pool.  
The following setup worked for me:
```
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.4'
        with:
          workload_identity_provider: 'projects/$myProjectNumber/locations/global/workloadIdentityPools/$workloadIdentityPool/providers/$myProvider'
          service_account: '$myServiceAccount@$myProjectName.iam.gserviceaccount.com'
          create_credentials_file: true
```

So far I only tested with the following firebase commands and they all completed successfully:
```
          firebase use $myProject --debug
          firebase hosting:sites:list --debug
          firebase projects:list --debug
```

I haven't looked into it in depth but perhaps specifying an [token_format](https://github.com/google-github-actions/auth/blob/9b6531516d83edfdfaca2912a78e8e271777d29c/dist/main/index.js) might not be required?
