### ISSUE TITLE
Parsing trouble for non-required extension parameters

### ISSUE THREAD

**Issue by alallema** [firebase/firebase-tools#3934]
### [REQUIRED] Environment info

**firebase-tools:** 9.23.0

**Platform:** macOS

### [REQUIRED] Test case

I'm not sure if it's a regression, but I found this [issue](https://github.com/firebase/firebase-tools/issues/3126) that seems pretty similar.
Installs an extension installation or emulator with the `--param` file as an argument. If there are optional parameters that are empty in the file, the next line will be read.
This issue seems to be present in the `v9.22.0` but not in the `v9.21.0`

### [REQUIRED] Steps to reproduce

*This is the `extension.yml` file:*
```yml
  - param: FIELDS_TO_INDEX
    label: Fields to index in Meilisearch
    description: >-
        What are the names of the fields you want to be indexed in MeiliSearch?
        Create a comma-separated list of the fields name, or leave blank to take all fields.
        The id field is always indexed even when omitted in the list.
    example: 'title,overview,release_date'
    validationRegex: "^[^,]?[a-zA-Z-_0-9,]*[^,]$"
    validationErrorMessage:
      Fields must be given through a comma-separated list.
    default: ''
    required: false

  - param: SEARCHABLE_FIELDS
    label: Fields in which to search. - Optional
    description: >-
      What are the names of the fields you want to make searchable in MeiliSearch?
      This features is optional. See [the documentation about it](https://docs.meilisearch.com/reference/features/field_properties.html#searchable-fields)
      for more information.
      Create a comma-separated list of fields, or leave blank to include all fields.
    example: 'title,overview,release_date'
    validationRegex: "^[^,]?[a-zA-Z-_0-9,]*[^,]$"
    validationErrorMessage:
      Fields must be given through a comma-separated list.
    default: ''
    required: false
```

*This is the `param.env` file:*
```
LOCATION=us-central1
COLLECTION_PATH=movies
FIELDS_TO_INDEX=
SEARCHABLE_FIELDS=
MEILISEARCH_INDEX_NAME=movies
MEILISEARCH_HOST='http://127.0.0.1:7700'
MEILISEARCH_API_KEY='masterKey'
```

```bash
firebase ext:install <extension-name> --params=params.env --project=<project-id>
```

### [REQUIRED] Expected behavior

The optional parameter does not have to be filled in.

### [REQUIRED] Actual behavior

**This is a print of `process.env`**
```bash
{"location":"us-central1","collectionPath":"movies","host":"http://127.0.0.1:7700","apiKey":"masterKey","indexUid":"movies","fieldsToIndex":"SEARCHABLE_FIELDS=","searchableFields":"","severity":"INFO","message":"Initializing extension with configuration"}
```

**Output:**
```
Error: ; RESOURCE_ERROR at /deployments/firebase-ext-firestore-meilisearch-search-9djc/resources/indexingWorker: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Function failed on loading user code. This is likely due to a bug in the user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation."}
```

**Output with the param file modified as follows:**
```yml
LOCATION=us-central1
COLLECTION_PATH=movies
FIELDS_TO_INDEX=''
SEARCHABLE_FIELDS=
MEILISEARCH_INDEX_NAME=movies
MEILISEARCH_HOST='http://127.0.0.1:7700'
MEILISEARCH_API_KEY='masterKey'
```
```
Error: MEILISEARCH_INDEX_NAME has not been set in the given params file and there is no default available. Please set this variable before installing again.
```
