### ISSUE TITLE
Unable to find a valid endpoint for function mail

### ISSUE THREAD

**Issue by christianloosli** [firebase/firebase-tools#4792]
### [REQUIRED] Environment info

**firebase-tools:** 11.4.0

**Platform:** macOS and Github Actions

### [REQUIRED] Steps to reproduce

`firebase deploy --only hosting:sometarget`  or 
```
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}'
          projectId: xxxxxx
          channelID: live
          target: ${{ env.TARGET }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```
### [REQUIRED] Expected behavior

Should deploy successfully, because last deployment succeeded on 17 Jun without code changes.

```
***
  details_url: 'https://xxx.web.app/',
  conclusion: 'success',
  output: ***
    title: 'Production deploy succeeded',
    summary: '[xxx.web.app](https://xxx.web.app/)'
  ***
***
```

### [REQUIRED] Actual behavior

Deployment fails with the following error message:
````
  ***
    "status": "error",
    "error": "Unable to find a valid endpoint for function mail"
  ***
```
<!-- Run the command with --debug flag, and include the logs below. -->
