### ISSUE TITLE
Firebase deployment without token fails

### ISSUE THREAD

**Issue by JFGHT** [firebase/firebase-tools#5340]
Due to the new Firebase warning:

> ⚠  Authenticating with `--token` is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS`: https://cloud.google.com/docs/authentication/getting-started

We decided to implement it as it should be.

### [REQUIRED] Environment info

**firebase-tools:** 11.18.0

**Platform:** Github Actions with ubuntu-latest and pnpm.

### [REQUIRED] Test case

```yaml
name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test:unit

      - name: Run build
        run: pnpm build

      - name: Install Functions Deps
        shell: bash
        run: |
          cd functions && pnpm i

      # Future code for deploying without token
      - name: Decoding base64 Credentials
        shell: bash
        run: echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }} | base64 --decode > credentials.json

      - name: Save credentials into environment variables
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=./credentials.json" >> $GITHUB_ENV

      - name: Deploy to Firebase
        shell: bash
        # Using GOOGLE_APPLICATION_CREDENTIALS env
        run: |
          ./node_modules/.bin/firebase deploy --non-interactive

      - name: Remove credentials file
        if: success() || failure()
        run: rm credentials.json
```

### [REQUIRED] Steps to reproduce

- Generate the service account from the Firebase project.
- Encode it into base64, save it in Github secrets as GOOGLE_APPLICATION_CREDENTIALS_BASE64.
- Push anything to `main` branch.

### [REQUIRED] Expected behavior

Firebase should deploy as expected.

### [REQUIRED] What actually happens:

![image](https://user-images.githubusercontent.com/6596120/207860168-c920e7ca-99e4-450d-a614-96d177bcb0b5.png)
