### ISSUE TITLE
Deployment of Nextjs project fails after updating to 12.2.0

### ISSUE THREAD

**Issue by ydalir** [firebase/firebase-tools#5890]
Hello, we ran into an issue today with our firebase deployment. The github action we use installs the latest firebase-tools version, e.g. 12.2.0, which breaks our build. Explicitly setting the firebase-tools version back to 12.1.0 fixes the issue. We suspect the issue may be some of the changes around rewrites in https://github.com/firebase/firebase-tools/pull/5716.

Because the problem arose in a CI environment, posting logs and running commands was difficult. Let me know if you need more information than provided here.

### [REQUIRED] Environment info

**firebase-tools:** 12.2.0

**Platform:** Ubuntu 22.04.2 LTS (Github Action)

### [REQUIRED] Test case

```
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ***
          firebaseServiceAccount: ***
          projectId: ***
          channelId: live
          entrypoint: ./***
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
```
### [REQUIRED] Steps to reproduce

Trigger github action with above workflow configuration

### [REQUIRED] Expected behavior

Github Action correctly builds and deploys entire Nextjs project to firebase, or fails and throws an error.

### [REQUIRED] Actual behavior

Github Action does not build project correctly but does not throw an error, and deploys mangled build.
