### ISSUE TITLE
Travis CI fails to deploy - Cannot find module 'ipaddr.js'

### ISSUE THREAD

**Issue by bob-lee** [firebase/firebase-tools#628]
### Version info

firebase-tools: 3.16.0

### Steps to reproduce

My project is hosting an express app on cloud function and can deploy from localhost with no problem but with Travis CI, each time I commit to `master` branch, it runs test / scripts ok but last `firebase deploy` fails consistently with error like:

> === Deploying to 'react-joanne'...
> i  deploying functions, hosting
> i  functions: ensuring necessary APIs are enabled...
> ✔  functions: all necessary APIs are enabled
> i  functions: preparing functions directory for uploading...
>
> Error: Error parsing triggers: Cannot find module 'ipaddr.js'

https://travis-ci.org/bob-lee/react-joanne

My [.travis.yml](https://github.com/bob-lee/react-joanne/blob/master/.travis.yml) looks like:

```
language: node_js
node_js:
  - 6
branches:
  only:
    - master
install:
  - yarn
  - CI=false yarn build:ssr
  - yarn fns:deps
after_success:
  - node_modules/.bin/firebase deploy --non-interactive --token "$FIREBASE_TOKEN" --project react-joanne
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_TOKEN"
  project: "react-joanne"
```
