### ISSUE TITLE
Mobile SDK API has not been used in project

### ISSUE THREAD

**Issue by yellowhat** [firebase/firebase-tools#6310]
### [REQUIRED] Environment info

**firebase-tools:** 12.5.1 

**Platform:** Ubuntu

### [REQUIRED] Test case

Hi,
after adding the `googlecloud/firestore-semantic-search@0.1.6` to our extensions:

```json
  "extensions": {
    "firestore-send-email": "firebase/firestore-send-email@0.1.26",
    "mailchimp-firebase-sync": "mailchimp/mailchimp-firebase-sync@0.5.2",
    "firestore-semantic-search": "googlecloud/firestore-semantic-search@0.1.6"
  }
```

we are not able to deploy extensions anymore via GitHub actions using a GCP Service Account key to authenticate:

```yaml
      - name: Decode Google Cloud Service Account key
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 -d > /tmp/creds.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/creds.json" >>"$GITHUB_ENV"

      - name: Deploy Firebase - functions
        run: |
          echo \"N\n\" | firebase deploy --only functions --interactive

      - name: Deploy Firebase except hosting
        run: |
          firebase deploy \
              --except functions,hosting \
              --project "$GOOGLE_CLOUD_PROJECT" \
              --debug
``` 

we get the following error:

```console
Error when checking App Developer TOS for xxx. This is expected if authenticated via a service account: FirebaseError: HTTP Error: 403, Firebase Extensions Terms of Service Private API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseextensionstos-pa.googleapis.com/overview?project=xxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

...

Error: HTTP Error: 403, Mobile SDK API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/mobilesdk-pa.googleapis.com/overview?project=xxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
[2023-08-24T07:51:19.965Z] Error Context: {
  "body": {
    "error": {
      "code": 403,
      "message": "Mobile SDK API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/mobilesdk-pa.googleapis.com/overview?project=xxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
      "status": "PERMISSION_DENIED",
      "details": [
        {
          "@type": "type.googleapis.com/google.rpc.Help",
          "links": [
            {
              "description": "Google developers console API activation",
              "url": "https://console.developers.google.com/apis/api/mobilesdk-pa.googleapis.com/overview?project=xxx"
            }
          ]
        },
        {
          "@type": "type.googleapis.com/google.rpc.ErrorInfo",
          "reason": "SERVICE_DISABLED",
          "domain": "googleapis.com",
          "metadata": {
            "consumer": "projects/xxx",
            "service": "mobilesdk-pa.googleapis.com"
          }
        }
      ]
    }
  },
  "response": {
    "statusCode": 403
  }
}
```

The project number matches the real project.

Additional info:

* the service account associate to that key has `owner` role on the GCP project
* Firebase Auth has been enabled via the Firebase UI
* If I run the steps of the workflow locally logged as the same service account I get the same error.
* If I run the steps of the workflow up to the `GOOGLE_APPLICATION_CREDENTIALS` and run `firebase login`, now on:

```console
$ firebase deploy --only extensions --debug
...
? Do you accept the Firebase Extensions User Terms of Service? (Y/n) 
```

Running CI after the extension has been deployed leads to the same error

Any suggestions?

Thanks

### [REQUIRED] Steps to reproduce

```bash
export GOOGLE_APPLICATION_CREDENTIALS=<path_to_json>
firebase deploy --only extensions
```

### [REQUIRED] Expected behavior

Extensions deployed

### [REQUIRED] Actual behavior

Error above
