### ISSUE TITLE
Build fails when using yarn in firebase-generated hosting yaml

### ISSUE THREAD

**Issue by erikmartinessanches** [firebase/firebase-tools#6637]
### [REQUIRED] Environment info

**firebase-tools: 13.0.2**

**Platform: macOS Sonoma 14.2**

### [REQUIRED] Test case

My [commit to my repository](https://github.com/erikmartinessanches/TrainingLog/tree/6e09b7041fe130a2d196d0f5834a7adca82f65eb).

### [REQUIRED] Steps to reproduce
First I ran `firebase init hosting:github` to make the yaml below. I manually changed the "run" and added one "run" section. (Abbreviated)
```
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn run build --verbose
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MINIPROJECT_90787 }}'
          projectId: miniproject-90787
```
Then trigger the github action.

### [REQUIRED] Expected behavior
Should build ok.

### [REQUIRED] Actual behavior
The error is (abbreviated)
```
Run yarn run build
yarn run v1.22.19
$ tsc && vite build
Version 5.3.3
tsc: The TypeScript Compiler - Version 5.3.3

COMMON COMMANDS

//shortened
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
