### ISSUE TITLE
Unable to deploy to firebase hosting for NextJS application, show 404 (not found) page

### ISSUE THREAD

**Issue by ZhuZean** [firebase/firebase-tools#8274]
### [REQUIRED] Environment info

**firebase-tools: 13.32.0**

**Platform: Ubuntu**

### [REQUIRED] Test case

I've built a website with Next js 13.5.4, and using Github Action to deploy the application whenever making a PR or deploying to the staging and production.

I'm using the [FirebaseExtended/action-hosting-deploy@v0](https://github.com/FirebaseExtended/action-hosting-deploy)  for Github Action deployment. 

I found Firebase shows a `404` page after I triggered the deployment 2 days ago after the firebase-tools published the latest version (13.32.0).

After digging into the problem, I found the deployment time was much shorter than before after the lastest version was published. It cost around 7 minutes to deploy the firebase preview channel but now it only takes 33 seconds.

#### 404 page from firebase hosting
<img width="500" alt="Image" src="https://github.com/user-attachments/assets/fb6535f3-bff0-41f3-aa55-bc8b29a7b72f" />

### [REQUIRED] Steps to reproduce

Example of the Github action file

```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: PR - Deploy to Firebase Hosting on PR
'on': pull_request
env:
  WEB_APPLICATION_ENV: development
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build:dev
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.ABC }}'
          projectId: 123
          target: 123
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
```

### [REQUIRED] Expected behavior

We can deploy the project to the firebase hosting.
<img width="800" alt="Image" src="https://github.com/user-attachments/assets/7ab9a8d2-9596-4435-bbf9-5939d0be54e2" />

### [REQUIRED] Actual behavior

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/10a50f9a-de4f-4600-b50d-c5feb9897cfb" />

**Comment by 0xApplePie** [comment]
We face the same issue, although we use NextJS 14. 
Our Pipelines for deployment do not work anymore. 
We had no deployment issues for months and did not change any deployment-related code.

for now use the old version:
`npm i -g firebase-tools@13.31.2`

**Comment by ZhuZean** [comment]
Hey @0xApplePie , do you use GitHub Action for deployment?

It keeps pulling the latest version of the Firebase tool during the Github Action deployment, although I installed the previous before 🤔 

<img width="1000" alt="Image" src="https://github.com/user-attachments/assets/54b006be-34f9-4090-9464-1bfe8d35ad4f" />

**Comment by 0xApplePie** [comment]
I am not familiar with Github Actions, we use Gitlab CI/CD. But it should work similarly, I think.

But it looks like you require, in the npx command, the latest version of firebase-tools.
Maybe change `npx firebase-tools@latest` to either just `npx firebase-tools` or `npx firebase-tools@13.31.2`

**Comment by ZhuZean** [comment]
@0xApplePie  Thank you!

I figured it out by indicating the `firebaseToolsVersion: "13.31.2"` in the deployment file.

<img width="759" alt="Image" src="https://github.com/user-attachments/assets/5778250e-3152-4ba8-8013-ac12808627d1" />

**Comment by chalosalvador** [comment]
@ZhuZean Thanks for reporting this. Are you still experiencing the issue? 
I have tried to reproduce it but the action is deploying the preview successfully.
You can see a minimal reproducible example repo here: https://github.com/chalosalvador/nextjs-deploy/pull/1

It uses the following Github action that looks like the one you are using with `firebase-tools@13.32.0`

```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: PR - Deploy to Firebase Hosting on PR
'on': pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
env:
  WEB_APPLICATION_ENV: development
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FB_TOOLS_DEV }}
          projectId: xx-yy-zz
          target: xx-yy-zz
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
```

There might be something specific I'm missing. Would you mind confirming you're still experiencing this and share any other relevant details?
