### ISSUE TITLE
Environment variables defined in apphosting.yaml are not bound to Cloud Run container

### ISSUE THREAD

**Issue by Tatsuho-Nagatomo** [firebase/firebase-tools#8307]
### [REQUIRED] Environment info

**firebase-tools:** 11.1.0

**Platform:** macOS

### [REQUIRED] Test case

Using Firebase App Hosting with Next.js, environment variables defined in apphosting.yaml under env are not being bound to Cloud Run deployments. This issue started occurring recently; previously, it worked as expected.

Here is an example of the configuration in apphosting.yaml:
```
env:
  - variable: NEXT_PUBLIC_ENV
    value: staging

  - variable: NEXT_PUBLIC_APP_URL
    value: https://example.asia-east1.hosted.app/
```

### [REQUIRED] Steps to reproduce

1. Define environment variables in the apphosting.yaml file for a Firebase App Hosting deployment using Next.js as described above.

2. Deploy the application via github with cloud build

3. Check Cloud Build logs; environment variables appear correctly bound during the build:
```
env:
- variable: NEXT_PUBLIC_ENV
  value: staging
  availability:
  - BUILD
  - RUNTIME
- variable: NEXT_PUBLIC_APP_URL
  value: https://example.asia-east1.hosted.app/
  availability:
  - BUILD
  - RUNTIME
```
4. Inspect the generated revision YAML on Cloud Run. Observe that the environment variables are missing under the container spec:
```
spec:
  containerConcurrency: 80
  timeoutSeconds: 300
  serviceAccountName: firebase-app-hosting-compute@***.iam.gserviceaccount.com
  containers:
  - name: example-1
    image: asia-east1-docker.pkg.dev/***
    ports:
    - name: http1
      containerPort: 8080
    resources:
      limits:
        cpu: '1.00'
        memory: 512Mi
    startupProbe:
      timeoutSeconds: 240
      periodSeconds: 240
      failureThreshold: 1
      tcpSocket:
        port: 8080
```

### [REQUIRED] Expected behavior

Environment variables defined in apphosting.yaml should be correctly bound to the Cloud Run revision and appear under containers.env, as was previously the case:
```
spec:
  containerConcurrency: 80
  timeoutSeconds: 300
  serviceAccountName: firebase-app-hosting-compute@***.iam.gserviceaccount.com
  containers:
  - name: example-1
    image: asia-east1-docker.pkg.dev/***
    ports:
    - name: http1
      containerPort: 8080
    env:
    - name: NEXT_PUBLIC_ENV
      value: staging
    - name: NEXT_PUBLIC_APP_URL
      value: https://example.asia-east1.hosted.app/
```

### [REQUIRED] Actual behavior

Currently, the environment variables are not bound at runtime, despite showing as correctly processed during build logs. Cloud Run deployments lack the specified environment variables entirely.
