### ISSUE TITLE
Deploy fails setting artifact cleanup policy via Service Account in GitHub Actions (Next.js webframeworks) despite permissions

### ISSUE THREAD

**Issue by MauricioMontoya** [firebase/firebase-tools#8456]
### [REQUIRED] Environment info

**firebase-tools:** `latest` (Observed resolving to 14.2.0 in GitHub Actions runner logs during initial attempts)

**Platform:** GitHub Actions runner (`ubuntu-latest`, runner logs show Node v22.14.0 being used, although project targets Node v20)

### [REQUIRED] Test case

* Next.js v15.3.1 project using App Router and middleware (specifically `src/middleware.ts` for internationalization with `next-intl`).
* Firebase project configured for Firebase Hosting integrated with Web Frameworks.
* Deployment via `FirebaseExtended/action-hosting-deploy@v0` GitHub Action.
* Authentication using a Service Account key stored as a GitHub Secret (`FIREBASE_SERVICE_ACCOUNT`).
* The Service Account has been granted broad IAM roles, including `Firebase Admin`, `Artifact Registry Admin`, and `Service Account User` (granted on the default App Engine SA `[PROJECT_NUMBER]-compute@developer.gserviceaccount.com`).
* The `FIREBASE_CLI_EXPERIMENTS=webframeworks` environment variable is enabled for the deployment step in the GitHub Action.
* `firebase.json` includes Hosting configuration with rewrites pointing to the auto-generated Cloud Function. It also includes Firestore and Storage rules configurations.

### [REQUIRED] Steps to reproduce

* Set up a Firebase project and a Next.js (v15+) project using middleware.
* Configure firebase.json for Hosting integration using webframeworks (either manually or letting firebase deploy detect it with the experiment enabled).
* Create a Service Account in GCP for the project.
* Grant the Service Account the IAM roles Firebase Admin and Artifact Registry Admin.
* Grant the Service Account the Service Account User role on the default App Engine compute service account ([PROJECT_NUMBER]-compute@developer.gserviceaccount.com).
* Set up a GitHub Actions workflow using FirebaseExtended/action-hosting-deploy@v0.
* Configure the action to use the Service Account key via GitHub Secrets (secrets.FIREBASE_SERVICE_ACCOUNT).
* Set the FIREBASE_CLI_EXPERIMENTS=webframeworks environment variable for the deploy step.
* Optionally, try adding args: --force to the action's with: block.
* Trigger the workflow (e.g., on push or pull_request).
* Observe the workflow logs.

### [REQUIRED] Expected behavior

The firebase deploy command executed by the GitHub Action completes successfully with exit code 0. All components (Hosting, Firestore rules, Storage rules, required Cloud Function for Next.js) are deployed, and the Artifact Registry cleanup policy is configured automatically without error, given the extensive permissions granted to the Service Account.

### [REQUIRED] Actual behavior

The deployment process executes the next build, uploads hosting files, and successfully deploys/updates the required Cloud Function (ssrvendelu). However, the process fails immediately after the function deployment success message with exit code 1. The specific error printed is:

`✔  functions[firebase-frameworks-vendelu:[SSRFUNCTION](us-central1)] Successful update operation.
... (function deployment summary) ...
⚠  functions: No cleanup policy detected for repositories in us-central1. This may result in a small monthly bill as container images accumulate over time.
Error: Functions successfully deployed but could not set up cleanup policy in location us-central1. Pass the --force option to automatically set up a cleanup policy or run 'firebase functions:artifacts:setpolicy' to manually set up a cleanup policy.
... (process failed with exit code 1) ...`

**Comment by steveoh** [comment]
This is not working on 14.2.1 which was released today. 

> Error: Functions successfully deployed but could not set up cleanup policy in location us-central1. Pass the --force option to automatically set up a cleanup policy or run 'firebase functions:artifacts:setpolicy' to manually set up a cleanup policy.

If I run that command it shows me

> $ firebase functions:artifacts:setpolicy
> i  A cleanup policy already exists that deletes images older than 1 days.
> i  No changes needed.

So something is not working properly in 14.

https://github.com/firebase/firebase-tools/issues/8378

**Comment by MauricioMontoya** [comment]
I found a workaround to deploy with GitHub Actions, add the following configuration to your **firebase-hosting-pull-request.yml** and **firebase-hosting-merge.yml**:

```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main # Trigger the workflow only on pushes to the main branch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE

      # Added: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js version 20 for compatibility
          cache: 'npm' # Cache npm dependencies

      # Install Firebase Functions dependencies (if you have a 'functions' directory)
      # If your functions are defined elsewhere or not used, you might remove/adjust this.
      - name: Install functions dependencies
        run: cd functions && npm ci # Navigate to functions dir and install dependencies using package-lock.json

      # Authenticate to Google Cloud Platform using the Service Account Key
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          # Use the Service Account key stored in GitHub Secrets.
          # Replace YOUR_SECRET_NAME with the actual name of your secret.
          credentials_json: ${{ secrets.YOUR_SECRET_NAME }}

      # Set up the Google Cloud SDK (gcloud CLI)
      - name: Setup GCP SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: your-project-id # Specify YOUR GCP project ID

      # Configure the Artifact Registry cleanup policy using gcloud
      # This step prevents the firebase deploy command from failing later
      # when it tries (and potentially fails) to set the policy itself.
      - name: Configure Artifact Registry cleanup policy
        run: |
          # Create a JSON file defining the cleanup policy
          cat <<EOF > cleanup-policy.json
          [
            {
              "name": "delete-old-artifacts",
              "action": {"type": "Delete"},
              "condition": {
                "olderThan": "7d",     # Delete artifacts older than 7 days
                "tagState": "any"      # Apply to tagged and untagged artifacts
              }
            }
          ]
          EOF
          # Apply the policy using gcloud to the specified repository
          # Replace 'your-project-id' if it's different for gcloud commands
          gcloud artifacts repositories set-cleanup-policies gcf-artifacts \
            --project=your-project-id \
            --location=us-central1 \
            --policy=cleanup-policy.json \
            --no-dry-run # Apply the policy immediately

      # Added: Install project dependencies using npm ci
      - name: Install dependencies
        run: npm ci # 'npm ci' is generally preferred over 'npm install' in CI for clean installs

      # Install the Firebase CLI globally in the runner
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Added: Build the Next.js project
      - name: Build project
        run: npm run build # This executes the "build" script in your package.json (likely "next build")

      # Existing step: Deploy the built project to Firebase Hosting live channel
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }} # Token for GitHub operations
          # Use the Service Account key stored in GitHub Secrets.
          # Replace YOUR_SECRET_NAME with the actual name of your secret.
          firebaseServiceAccount: ${{ secrets.YOUR_SECRET_NAME }}
          channelId: live # Deploy directly to the live channel
          projectId: your-project-id # Specify YOUR Firebase project ID
          # The action will automatically detect the Next.js framework (due to webframeworks experiment)
          # and deploy the necessary Cloud Function and hosting files.
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks # Enable experimental web frameworks support in Firebase CLI
```

I hope this help someone else trying to publish a NextJS App in Firebase using webframeworks from FIREBASE_CLI_EXPERIMENTS
