### ISSUE TITLE
Incorrect type `eventFilters` schema in extension-yaml.json

### ISSUE THREAD

**Issue by htsuruo** [firebase/firebase-tools#8630]
I ran into an issue while developing my extensions. The `eventFilters` parameter should accept an object with attributes and values, but the schema is defined as a string. As a result, the editor throws the following error.

> "alerttype": Unknown word.cSpell
Incorrect type. Expected "string".yaml-schema: https://raw.githubusercontent.com/firebase/firebase-tools/master/schema/extension-yaml.json

<img width="751" alt="Image" src="https://github.com/user-attachments/assets/3a6985d1-deac-4014-8903-f6b4548a6638" />

### [REQUIRED] Environment info

**firebase-tools: 14.4.0**

**Platform: macOS 15.4.1 (24E263)**

### [REQUIRED] Test case

Open `extension.yaml` file and define `eventFilters` parameter with some attribute.

For instance:

```yaml
eventTrigger:
  eventType: google.firebase.firebasealerts.alerts.v1.published
  triggerRegion: global
  eventFilters:
    - attribute: alerttype
      value: crashlytics.newFatalIssue
```

### [REQUIRED] Steps to reproduce

1. Clone [firebase/extensions](https://github.com/firebase/extensions) repository.
2. Open `firestore-bigquery-export` > `extensions.yaml`
3. You will find the error `eventFilters` parameter row.

### [REQUIRED] Expected behavior

It should be defined `object` instead of `string`.
https://github.com/firebase/firebase-tools/blob/99bf24a0bb5dfa7ebc03606368a28ce56581734a/schema/extension-yaml.json#L220-L223

### [REQUIRED] Actual behavior

Incorrect type. Expected "string".
